SwanHubX/SwanLab

- swanlab/server/api/experiment.py
- vue/src/components/SLStatusLabel.vue
- vue/src/i18n/en-US/experiment.json
- vue/src/store/modules/experiment.js
- vue/src/views/experiment/pages/index/components/ExperimentHeader.vue
- vue/src/views/experiment/pages/index/components/StopButton.vue
Now, we can press button to stop an experiment on SwanLab dashboard.
Closes: #107
> feat: stop experiment on dashboard

- swanlab/data/run/main.py
- swanlab/data/settings.py
default project name has setten as runtime folder name
Closes: #127
> default project name

- tailwind.config.js
- vue/src/App.vue
- vue/src/components/message/SLMessages.vue
Make the message component covered by all layouts.
> message above all

- swanlab/data/run/main.py
When the log level is None, no longer check its format.
Closes: #150
> when log_level is None

- swanlab/server/api/experiment.py
- swanlab/server/api/project.py
- vue/src/views/experiment/pages/chart/components/package/LineChart.vue
- vue/src/views/experiment/pages/index/components/ExperimentConfig.vue
When the value type is float, keep 4 valid numbers.
* solve #146 task 2
> fix number formatter

- swanlab/data/run/main.py
Set -1 when crashed, and reuse function
Closes: #146
> set -1 when crashed

- swanlab/data/system.py
在swanlab/data/system.py里增加一个函数，作用是获取训练项目git的分支名和该分支下最新commit的hash。
> add __get_git_branch_and_commit

- .github/ISSUE_TEMPLATE/ask for question.md
- .github/ISSUE_TEMPLATE/bug report.md
- .github/ISSUE_TEMPLATE/feature request.md
> refactor:delete issue title emoji

- swanlab/data/system.py
> get memory size

- README.md
- README_zh-hans.md
Modified the non-standard part of readme
> fix readme format

- swanlab/data/system.py
> bugfix: requirements '@file' problem

- swanlab/server/api/experiment.py
- swanlab/server/api/project.py
- swanlab/server/module/resp.py
What you wrote is not standard, and I changed it for you.
> change error code

- swanlab/log/log.py
> fix: params

- swanlab/data/system.py
增加获取每块显卡的GPU显存，为未来Environment部分的增加记录参数做准备。
> add gpu memory

- swanlab/data/system.py
构造了当前工作目录路径的获取函数，并添加至获取系统信息的函数中
Closes: #(issue)
Before your create a PR, please check to see if there is [an existing issue](https://github.com/SwanHubX/SwanLab/issues)
for this change. If not, please create an issue before you create this PR, unless the fix is very small.
Not adhering to this guideline will result in the PR being closed.
> feat:add __get_cwd()

- swanlab/env.py
> friendly error message for default swanlab init

- swanlab/data/run/main.py
- swanlab/data/run/utils.py
1. add json_serializable
2. optimize __check_cofig function
Closes:  #237
> feat: add json_serializable and optimize __check_cofig function

- swanlab/data/run/main.py
修复当check_config时，提前做ujson.dumps转换导致config变为字符串，后续处理错误的问题
> bugfix: config

- vue/src/views/home/components/ExprTable.vue
> fix: overflow

- swanlab/db/models/experiments.py
after deleting exp, can not create exp
> bug fix: delete experiment

- vue/src/i18n/en-US/home.json
- vue/src/i18n/zh-CN/home.json
- vue/src/store/modules/experiment.js
- vue/src/utils/time.js
- vue/src/views/experiment/pages/environment/pages/EnvIndex.vue
- vue/src/views/home/HomeView.vue
Experiment log dir: `swanlog path` + `experiment run_id`
Closes: #295
> refactor: log dir

- vue/src/charts/package/LineChart.vue
> fix step bug

- swanlab/db/utils/chart.py
The type of a multi exp chart should be the same as the accompanying chart of the corresponding tag.
> fix: chart type

- swanlab/__init__.py
- swanlab/data/__init__.py
> feat/add swanlab.Run

- vue/src/views/home/components/ExprTable.vue
> fix: remove event listener

- swanlab/data/modules/image.py
- vue/src/charts/package/ImageChart.vue
> ui: min height

- requirements.txt
- swanlab/api/__init__.py
- swanlab/api/auth/__init__.py
- swanlab/api/auth/login.py
- swanlab/api/cos.py
- swanlab/api/http.py
- swanlab/api/info.py
- swanlab/api/upload/__init__.py
- swanlab/cloud/_log_collector.py
- swanlab/data/run/exp.py
- swanlab/data/run/main.py
- swanlab/data/sdk.py
- swanlab/data/settings.py
- swanlab/db/models/experiments.py
- swanlab/error.py
- swanlab/utils/font.py
* 接入cos
* 接入创建项目、实验的api
* 接入标量实验api
* requests -> httpx
* 修复了一些bug
> Upload scalar metrics

- swanlab/data/sdk.py
* fix #464 , change entity to workspace
* update #418
> change entity to workspace

- swanlab/api/http.py
- swanlab/api/info.py
- swanlab/api/upload/__init__.py
- swanlab/cloud/dog/log_sniffer.py
- swanlab/data/sdk.py
- swanlab/db/models/experiments.py
> access config api

- swanlab/data/system/info.py
> add swanlab version

- swanlab/data/run/main.py
- swanlab/data/settings.py
- swanlab/data/system/info.py
* update #471 
* fix #473 
与swanlab相关的信息存在于swanlab字段下，前端需要同步更改
> add logdir

- swanlab/log/console.py
- vue/src/views/experiment/pages/log/LogPage.vue
> refactor: swanlog

- swanlab/api/http.py
- swanlab/data/sdk.py
> fix: upload error

- swanlab/api/__init__.py
- swanlab/data/sdk.py
> nest_asyncio.apply()

- swanlab/api/http.py
- swanlab/cloud/_log_collector.py
在每次请求时重建会话，能够解决 #507 的报错，但这并不优雅
> recreate session

- vue/src/utils/time.js
- vue/src/views/experiment/pages/index/components/DataTable.vue
修复两个bug
- 实验表格，当value为null时异常 close #479 
- 实验进行时，持续时间计算异常
> fix: exp summary table

- requirements.txt
- swanlab/api/__init__.py
- swanlab/api/auth/login.py
- swanlab/api/http.py
- swanlab/api/info.py
- swanlab/api/upload/__init__.py
- swanlab/cloud/_log_collector.py
- swanlab/cloud/dog/log_sniffer.py
- swanlab/cloud/start_thread.py
- swanlab/cloud/utils.py
- swanlab/data/run/main.py
- swanlab/error.py
- swanlab/package.json
- swanlab/utils/font.py
- test/unit/auth/pytest_login.py
更改异步单线程为同步多线程，以规避python环境异步编程的问题，close #507
> fix event error

- swanlab/data/sdk.py
> bugfix: omegaconf

- swanlab/package.json
> change api host

- vue/src/components/SLCheck.vue
> feat: disabled api for SLCkeck.vue

- swanlab/data/run/exp.py
This reverts commit ba31825994fb3ad78282776f21909c38e41a233d.
revert和实验对象相关的更改
> Revert "fix: Image-matplotlib"

- swanlab/package.py
- test/unit/pytest_package.py
> add-timeout

- swanlab/integration/accelerate.py
- test/integration/accelerate/accelerate_train.py
- test/integration/accelerate/requirements.txt
- test/integration/accelerate/train.py
完成huggingface accelerate集成
增加accelerate 测试代码
参考huggingface accelerate文档增加了集成，参考文档如下
https://huggingface.co/docs/accelerate/usage_guides/tracking
Closes: 无
在test/integration/accelerate/train.py中包含相应的测试代码
> 集成了huggingface accelerate

- swanlab/api/upload/__init__.py
- swanlab/api/upload/model.py
- test/unit/api/upload/test_model.py
修复上传运行时信息的bug，此部分主要思想为：
1. 如果周期内只有单个信息需要上传，就直接上传，否则跳转步骤2
2. 如果周期内有多条信息，按照创建时间进行比较，并且保证每个信息为最新的信息
---
之前在创建时出现创建时间错误的问题，导致步骤二出现问题。现在添加了单元测试
> fix create

- swanlab/data/callback_local.py
> delete bytes utf-8

- swanlab/integration/accelerate.py
1. 优化与accelerate的集成，将__init__的参数替换为swanlab.init的标准参数
2. 修复了log_images函数的Bug
> Update integration accelerate

- swanlab/data/callback_cloud.py
- swanlab/data/callback_local.py
- swanlab/data/modules/image/__init__.py
- swanlab/package.json
1. 改进了`tp(val)`的报错打印方式
2. 改进了云端日志显示的方式
> 修复云端版和本地版bug报错输出信息不准确的问题

- README.md
- README_cn.md
> READNE - add google colab

- CONTRIBUTING.md
- tutils/check.py
增加设置跳过云测试环境变量的注释
增加了mac，linux和win的命令
> 增加设置跳过云测试环境变量的注释

- swanlab/data/run/config.py
- test/unit/data/run/test_config.py
测试代码已经写在test/unit/data/run/test_config.py的test_parse函数当中
> add dataclass auto translate

- swanlab/api/http.py
- swanlab/cli/commands/task/launch.py
- swanlab/data/callback_cloud.py
- swanlab/data/sdk.py
- swanlab/package.json
* 在init的时候增加private参数，用于判断是否设置项目为私有，默认为私有。如果当前项目已经创建，此参数无效。
* 修复launch的一些命令行提示bug
* 版本修改为0.3.15-alpha.1，测试时请使用最新版 @Feudalman
> add private param

- swanlab/api/http.py
- swanlab/cli/commands/task/__init__.py
- swanlab/cli/commands/task/list.py
- swanlab/cli/commands/task/search.py
- swanlab/cli/commands/task/utils.py
* 修复入口文件路径问题
* 修复了一些神奇的bug
* 调整ui
* 增加新命令：swanlab task search
* http请求头增加sdk版本号
> add search api

- swanlab/cli/commands/task/search.py
- swanlab/data/callback_cloud.py
- swanlab/package.json
* 修复runtime为task的回调问题
* 修复显示问题
* 0.3.15-alpha.2
> fix:callback

- requirements-dev.txt
- swanlab/api/http.py
- swanlab/cli/commands/task/launch.py
- swanlab/cli/commands/task/list.py
- swanlab/cli/commands/task/search.py
- swanlab/cli/commands/task/utils.py
- swanlab/data/callback_cloud.py
- swanlab/package.json
- swanlab/package.py
- test/unit/_/setup.py
- test/unit/cli/test_cli_task.py
- test/unit/test_package.py
- tutils/setup.py
修复目前launch已知问题：
此外，新增了一些测试函数，当launch相关接口响应3xx时，告诉用户需更新到最新版本
新版本：0.3.15-alpha.3
> fix launch bugs

- swanlab/api/auth/login.py
- swanlab/api/http.py
- swanlab/cli/commands/task/list.py
- swanlab/cli/commands/task/search.py
- swanlab/package.json
- swanlab/package.py
- test/unit/api/auth/test_login.py
* 调整了ui
* 在task运行时下不保存用户api key
> fix launch some bugs

- swanlab/cli/commands/task/__init__.py
- swanlab/cli/commands/task/launch.py
- swanlab/cli/commands/task/list.py
- swanlab/cli/commands/task/search.py
- swanlab/cli/commands/task/stop.py
- swanlab/cli/commands/task/utils.py
- swanlab/package.json
新版本：`v0.3.15-beta`，旧版本的pypi将在新版本发布一段时间后删除。
更新以下几个方面：
> v0.3.15-beta

- swanlab/cli/commands/task/utils.py
- swanlab/package.json
> fix timezone

- requirements.txt
- swanlab/package.json
修复swanboard部分出现的`import error`问题
> update swanboard version

- swanlab/cli/commands/uploader/__init__.py
cli: swanlab upload 
上传时携带目录名：
1. 默认为指定目录名
2. 用户指定 -n 后设置为数据集名称
> fix(cli): upload with folder

- script/README.md
- script/explort_csv_from_local.py
增加一个用于临时将本地日志文件导出为csv的脚本，方便用户对记录的日志进行进一步处理
> add export local data script

- swanlab/data/run/system/info.py
在「环境」-「系统硬件」中增加“CUDA版本”
Closes: #678
> feat: add cuda version

- CONTRIBUTING.md
> add description about cloud test

- swanlab/cli/commands/task/list.py
- swanlab/cli/commands/task/search.py
- swanlab/cli/commands/task/utils.py
- swanlab/cli/utils.py
- swanlab/package.json
- test/unit/cli/test_cli_task.py
Add task output download uri.
> :bell:  开发环境部署了还要测一下
> feat(cli): add task's output

- swanlab/cli/commands/task/list.py
- swanlab/cli/commands/task/search.py
- swanlab/cli/commands/task/utils.py
change raw url to markdown format
> fix(cli): change raw url to markdown format

- requirements.txt
> force choice version

- README.md
- README_EN.md
- README_JP.md
- README_RU.md
> docs: readme more language

- swanlab/integration/pytorch_lightning.py
> fix: lightning settings to public

- README.md
- README_EN.md
- README_JP.md
- README_RU.md
> docs: update README

- requirements.txt
- swanlab/data/callback_cloud.py
- swanlab/data/cloud/start_thread.py
- swanlab/data/cloud/sysmetrics_collector.py
- swanlab/data/run/exp.py
- swanlab/data/run/main.py
This pull request implements the hardware information upload feature.
It allows the training experiment to collect and upload hardware metrics, includes:
- System: **CPU usage** (totally & per core), **Memory usage**
- GPU: **Temperature**, **Load**, **Memory**
- Network: **I/O by Network**
- SwanLab Run: **CPU usage** (by core), **Memory usage**, **Disk I/O** by SwanLab
* feat: #136 
* feat: #721
>  实现硬件监控基础数据采集

- README.md
> docs: add changelog

- swanlab/env.py
* 删除临时域名
This reverts commit 71213430ff45c33b65018c684ca13dca3e4d2ee3.
> Revert "fix: temporary domain (#756)"

- requirements.txt
> chore: add setuptools for build

- .github/workflows/test-when-pr.yml
为单元测试添加重试机制，因为不知道为啥反正单元测试有时候会失败，但是重试又好了，特别是涉及到文件操作的就经常出点问题。。
> feat: retry test

- README.md
This pull request includes a small change to the `README.md` file. The change adds a new promotional badge with a link to HelloGitHub.
> docs: hello github badge

- swanlab/integration/accelerate.py
- swanlab/integration/fastai.py
- swanlab/integration/keras.py
- swanlab/integration/lightgbm.py
- swanlab/integration/pytorch_lightning.py
- swanlab/integration/sb3.py
- swanlab/integration/torchtune.py
- swanlab/integration/transformers.py
- swanlab/integration/xgboost.py
Closes: #838 
This pull request introduces a new method `update_config` across multiple integration modules in the `swanlab` package. This method allows for updating the configuration dynamically. Additionally, some import statements have been updated to include the `Dict` type from the `typing` module.
New `update_config` method added:
* [`swanlab/integration/accelerate.py`](diffhunk://#diff-21e590433731e838e8bae1b8246bbf56d138a82411bc41b4d05e41be289be224R103-R105): Added `update_config` method to update the configuration using the provided dictionary.
* [`swanlab/integration/fastai.py`](diffhunk://#diff-ed8fe2527ae188f2eda98a2415f11505709dce71daadc06c73026cda07fd9129L14-R14): Added `update_config` method and updated import statements to include `Dict`. …
> feat: add update_config function

- swanlab/data/callbacker/cloud.py
- swanlab/log/__init__.py
- swanlab/log/console.py
- swanlab/log/log.py
> fix: console recorder not enabled in cloud mode

- README.md
- README_EN.md
- README_JP.md
- README_RU.md
- swanlab/integration/huggingface.py
> fix: hf integration

- swanlab/plugin/notification.py
- WebHook Callbacks for LarkBot, DingTalkBot, WxWorkBot .....(Any bots supporting webhook url could be supported
- Except for Lark, both DingtalkBot and WxWork Bot need to be configured in group (DEVELOPER MODE MUST BE REQUIRED)
> feat: support webhook callback (Lark & Dingtalk & WxWork)

- swanlab/data/run/metadata/hardware/gpu/nvidia.py
- test/unit/data/run/metadata/hardware/gpu/test_nvidia.py
为系统图表添加GPU显存使用情况 **GPU Memory Allocated(MB)**
1. feat: add `gpu_mem_value` for `GpuCollector`
2. fix: change a key name (`ptc` -> `pct`)
3. test: add max_gpu_mem
Closes: #801
> feat: 'GPU Memory Allocated(MB)' for system monitor

- requirements-dashboard.txt
- swanlab/plugin/writer.py
> fix: del print

- swanlab/integration/transformers.py
> fix: transformers integration add step

- swanlab/data/run/metadata/hardware/__init__.py
- swanlab/data/run/metadata/hardware/cpu.py
- swanlab/data/run/metadata/hardware/disk.py
- swanlab/data/run/metadata/hardware/memory.py
- swanlab/data/run/metadata/hardware/network.py
- swanlab/data/run/metadata/hardware/soc/apple.py
- swanlab/data/run/metadata/hardware/type.py
- swanlab/data/run/metadata/hardware/utils.py
- swanlab/package.json
- test/unit/data/run/metadata/hardware/test_disk.py
- test/unit/data/run/metadata/hardware/test_network.py
- test/unit/data/run/metadata/hardware/test_utils.py
Closes: #882 
This pull request introduces new functionality for collecting disk and network information in the `swanlab` project. The changes include adding new modules for disk and network data collection, updating the hardware metadata initialization, and adding relevant utility functions.
New functionality for hardware data collection:
* [`swanlab/data/run/metadata/hardware/__init__.py`](diffhunk://#diff-fbb1cf41fbfa0ee3c58958c51b8905c870f7c5a02e8c5cc89939d2407a56be47R16-R17): Added imports for `get_disk_info` and `get_network_info`, and included these functions in the `get_hardware_info` method to collect disk and network information. [[1]](diffhunk://#diff-fbb1cf41fbfa0ee3c58958c51b8905c870f7c5a02e8c5cc89939d2407a56be47R16-R17) …
> feat: disk io and network sent receive

- swanlab/package.json
- test/unit/data/run/metadata/hardware/test_disk.py
优化一下这一块，以支持以下两种源码安装方式：
```bash
pip install -e .
pip install git+https://github.com/SwanHubX/SwanLab
```
> swanlab package version

- swanlab/api/cos.py
This pull request includes improvements to the `upload_files` method in the `swanlab/api/cos.py` file to handle failed submissions more gracefully and a minor import statement cleanup.
Handling failed submissions:
* [`swanlab/api/cos.py`](diffhunk://#diff-c244308c30ca85e7b147e880be01b79653f7d5dfdc8514acde788490e0147958R72-R86): Modified the `upload_files` method to catch `RuntimeError` exceptions when submitting tasks to the `ThreadPoolExecutor`. Failed buffers are retried individually after the initial batch submission. This change addresses the issue where `executor.submit` may fail due to limited threads or a closed thread pool. For #889 
Import statement cleanup:
* [`swanlab/api/cos.py`](diffhunk://#diff-c244308c30ca85e7b147e880be01b79653f7d5dfdc8514acde788490e0147958L10-R10): Changed …
> fix: concurrent error

- swanlab/data/modules/object3d/object3d.py
> fix: object 3d error type infer

- swanlab/data/run/metadata/hardware/npu/ascend.py
- swanlab/integration/accelerate.py
- swanlab/integration/fastai.py
- swanlab/integration/huggingface.py
- swanlab/integration/mmengine.py
- swanlab/integration/pytorch_lightning.py
- swanlab/integration/sb3.py
- swanlab/integration/torchtune.py
- swanlab/integration/transformers.py
- swanlab/integration/ultralytics.py
- swanlab/integration/xgboost.py
1. Environmental: added for cann version
2. Fixed some documentation links in the integration code.
> feat: ascend cann version

- README.md
- README_EN.md
- README_JP.md
- README_RU.md
- add discord & slack notification page
- Redirect to English mode page in non Chinese README docs
> fix(docs): en redirection

- swanlab/data/run/metadata/hardware/gpu/nvidia.py
- test/unit/data/run/metadata/hardware/gpu/test_nvidia.py
for hardware minitor:
- add `GPU Time Spent Accessing Memory (%)` （GPU 访问内存所花费的时间百分比）
Closes: #908
> feat: gpu time of memory

- swanlab/data/callbacker/cloud.py
- swanlab/data/cloud/log_collector.py
- swanlab/data/run/main.py
- swanlab/data/run/metadata/__init__.py
- swanlab/data/run/metadata/hardware/__init__.py
- swanlab/data/run/metadata/hardware/disk.py
- swanlab/data/run/metadata/runtime.py
- swanlab/data/sdk.py
- swanlab/log/console.py
- swanlab/swanlab_settings.py
- test/unit/log/test_log.py
- test/unit/test_swanlab_settings.py
该拉取请求包含多项改进，旨在优化`swanlab`项目中的运行时信息处理、日志记录和设置管理功能。主要变更涉及新增conda环境信息收集支持、重构导入逻辑，以及更新设置管理机制以提升灵活性和可控性。
* [`swanlab/data/callbacker/cloud.py`](diffhunk://#diff-733d6742a0ed52a329f3872a2f17de48637ce80a1af7f2a7a41a975d1d858972R148-R150)：通过将`r.conda.info`纳入运行时信息更新，新增conda环境信息收集功能
* [`swanlab/data/run/main.py`](diffhunk://#diff-716884b2803891f14f0e31a96ce3c380a52b38283304a509d29b4caa9d9abceaR125-L136)：更新运行时信息收集逻辑，根据设置条件性包含依赖项和conda信息
* [`swanlab/data/cloud/log_collector.py`](diffhunk://#diff-e2cd41845d2e3598d7358fde1350c9ed190cc9222691b4630e7472a91a4495e7L12-L31)：重构导入结构提升可读性与可维护性，取消硬编码的上传间隔，改用基于设置的动态间隔 [[1]](diffhunk://#diff-e2cd41845d2e3598d7358fde1350c9ed190cc9222691b4630e7472a91a4495e7L12-L31) [[2]](diffhunk://#diff-e2cd41845d2e3598d7358fde1350c9ed190cc9222691b4630e7472a91a4495e7R34) …
> refactor: settings

- swanlab/data/run/metadata/hardware/__init__.py
- swanlab/data/run/metadata/hardware/mlu/cambricon.py
- swanlab/data/run/metadata/hardware/npu/cambricon.py
环境-系统硬件与硬件监控：增加对寒武纪的记录
Closes: #727
> feat: env cambricon

- swanlab/sync/wandb.py
> fix snyc wandb finish

- swanlab/data/run/metadata/hardware/__init__.py
- swanlab/data/run/metadata/hardware/mlu/cambricon.py
1. 增加了硬件监控-寒武纪MLU的温度和功率
2. 将`cambrican`拼写改为`cambricon`，前端可能需要进行适配 @SAKURA-CAT
> feat: cambricon mlu temperature and power

- swanlab/data/run/metadata/hardware/__init__.py
- swanlab/data/run/metadata/hardware/mlu/cambricon.py
> fix: move cambricon from npu to mlu

- swanlab/data/run/metadata/hardware/gpu/nvidia.py
- swanlab/data/run/metadata/hardware/memory.py
- swanlab/data/run/metadata/hardware/mlu/cambricon.py
- swanlab/data/run/metadata/hardware/npu/ascend.py
- swanlab/data/run/metadata/hardware/soc/apple.py
> fix: memory type

- README.md
- README_EN.md
> docs: add evalscope

- swanlab/api/http.py
> feat: trace id for backend

- swanlab/data/run/metadata/hardware/gpu/nvidia.py
> fix: pynvml version conflict

- swanlab/data/run/metadata/runtime.py
Closes: #945 
增加了对操作系统发行版的检测，比如一个ubuntu系统：
> feat: os pretty name

- swanlab/api/openapi/experiment.py
- swanlab/api/openapi/main.py
- test/unit/api/openapi/test_experiment.py
获取一个exp状态，将三个参数都暴露出去让用户填写。第一次接触这个项目，如有开发不符请及时联系我，谢谢
开发openapis
> Add exp status

- README.md
- README_EN.md
- swanlab/data/run/metadata/hardware/__init__.py
- swanlab/data/run/metadata/hardware/gpu/moorethread.py
支持摩尔线程系统环境采集
设计文档：
https://rjwalmzfj2.feishu.cn/docx/BSxqdHbOxowiMSxjIY4cA6xBnGf
示例项目（需前端适配）
https://swanlab.cn/@nexisato/MUSA-Project-Demo
> feat: support moorethreads collector

- swanlab/integration/accelerate.py
- swanlab/integration/fastai.py
- swanlab/integration/paddlenlp.py
- swanlab/integration/pytorch_lightning.py
- swanlab/integration/sb3.py
- swanlab/integration/torchtune.py
- swanlab/integration/transformers.py
- swanlab/integration/ultralytics.py
Add tags to the integrated framework
> feat: add integration tags

- swanlab/api/http.py
This pull request includes a small change in the `mount_project` method within the `swanlab/api/http.py` file. The change removes an unused variable `proj_info`, simplifying the code.
> chore: some misc

- swanlab/data/run/metadata/hardware/gpu/metax.py
修复 metax 数据格式：
1. 删除 gpu_map 中多余的 "maca" 字段
2. 更新 gpu_memory、gpu_name 为 memory 和 name
> fix: metax type

- swanlab/data/run/config.py
> feat: mmengine config

- swanlab/data/run/metadata/requirements.py
> fix: pip list freeze

- swanlab/converter/wb/wb_converter.py
> fix: #1084

- swanlab/cli/commands/converter/__init__.py
- swanlab/converter/mlf/mlf_converter.py
- swanlab/converter/tfb/tfb_converter.py
- swanlab/converter/wb/wb_converter.py
将converter中的`cloud`参数换成更先进的`mode`参数
> feat: change wb converter params `mode`

- swanlab/integration/ray.py
Closes: #1113 
```python
import random
from ray import tune
from swanlab.integration.ray import SwanLabLoggerCallback
def train_func(config):
offset = random.random() / 5
for epoch in range(2, config["epochs"]):
acc = 1 - (2 + config["lr"]) ** -epoch - random.random() / epoch - offset
loss = (2 + config["lr"]) ** -epoch + random.random() / epoch + offset
tune.report({"acc": acc, "loss": loss})
tuner = tune.Tuner(
train_func,
param_space={
"lr": tune.grid_search([0.001, 0.01, 0.1, 1.0]),
"epochs": 10,
},
run_config=tune.RunConfig(
callbacks=[SwanLabLoggerCallback(project="Ray_Project")],
),
)
results = tuner.fit()
```
> feat: integration ray

- swanlab/data/sdk.py
- test/unit/data/test_sdk.py
1. 修复`merge_settings`引发的bug
2. swanlab.init增加reinit参数
> feat: reinit

- swanlab/sync/tensorboard.py
- swanlab/sync/wandb.py
- test/sync_mlflow.py
- test/sync_tensorboardX.py
- test/sync_tensorboard_torch.py
- test/sync_wandb.py
1. 添加sync_mflow的测试，补充sync_wandb、sync_tensorboard*的测试
2. sync_wandb增加对Image的适配及部分参数
3. sync_tensorboardX、sync_tensorboard_torch增加对Text、scalars的适配
> feat: improve sync series

- swanlab/data/sdk.py
- test/unit/data/test_sdk.py
> feat: match online mode

- README.md
- README_EN.md
Add lerobot tutorial case in README
> docs(readme): add lerobot guide in readme

- README.md
- README_EN.md
- README_JP.md
- README_RU.md
1. 增加关于MLX-LM框架的集成链接
2. 增加SwanLab文档助手的教程链接
> docs(readme): integration mlx lm

- requirements.txt
- swanlab/data/run/metadata/hardware/gpu/nvidia.py
Deprecated Pynvml
- https://pypi.org/project/pynvml/
-
> feat: deprecated pynvml
