README_zh-hans.md

fix broken link.
Be careful not to write Markdown directly below HTML syntax; you need an empty line.

fix broken link in readme

---

.github/workflows/publish-to-pypi.yml

修改 Action 在推送标签后即发布版本到 PyPI，并发布到 Release，然后再手动编辑完善内容。发布后的 Release 如下所示：
> https://github.com/swpfY/SwanLab/releases/tag/v0.0.12
Closes: #174

feat: automatic release

---

swanlab/data/system.py

注释掉data/system.py中的swanlog.warning，比如没有检测到Git的报错信息不应该让用户看到，只应开发者可以看到。
Fix： #217

Annotation swanlog.warning

---

swanlab/server/controller/project.py
swanlab/server/router/project.py
vue/src/components/SLCopy.vue
vue/src/i18n/en-US/experiment.json
vue/src/i18n/en-US/home.json
vue/src/i18n/zh-CN/experiment.json
vue/src/i18n/zh-CN/home.json
vue/src/store/modules/project.js
vue/src/views/experiment/pages/environment/components/EnvItem.vue
vue/src/views/experiment/pages/environment/components/EnvItems.vue
vue/src/views/experiment/pages/environment/pages/EnvIndex.vue
vue/src/views/home/HomeView.vue

Hover environment item to show copy button.
Closes: #208

feat: hover copy

---

prisma/schema.prisma
swanlab/db/models/charts.py

本项目无法在代码中使用到 [Prisma](https://www.prisma.io/)，引入 [Prisma](https://www.prisma.io/) 是为了方便对数据库建模和查看，还有对于本地开发测试来说后续可考虑使用其实现更方便地[迁移](https://www.prisma.io/docs/orm/prisma-migrate/getting-started)和导入模拟数据。

prisma: model schema

---

swanlab/log/console.py
swanlab/server/controller/experiment.py
test/_server.py
vue/src/layouts/ExperimentLayout.vue
vue/src/views/experiment/pages/log/LogPage.vue
vue/src/views/home/HomeView.vue

To get the latest 6000 pieces of data, log files must be sorted by time using `datetime.strptime`.
The point is we should import `datetime` as `from datetime import datetime` instead of `import datetime`.
Closes: #293

fix: time format

---

swanlab/data/run/exp.py

对 #307 提供了支持，记录了最大/最小值时的步数，数据结构如下：

record max step and min step

---

swanlab/server/controller/experiment.py
vue/src/charts/components/LineChartLegend.vue
vue/src/charts/package/LineChart.vue

legend component

---

vue/src/charts/package/ImageChart.vue

1. 是放大之后增加下载按钮
2. 在放大图表后点击图片详情，叉掉弹窗之后，应该回到放大图表的弹窗

fix zoom logic

---

swanlab/server/controller/experiment.py

Delete useless charts with destroying experiment
Closes: #352

fix: delete charts with experiment destroying

---

vue/src/views/home/HomeView.vue

fix: undefined table value

---

vue/src/charts/package/AudioChart.vue
vue/src/layouts/main/components/HeaderBar.vue

fix: blobs buffer

---

swanlab/data/sdk.py
swanlab/data/utils/file.py
swanlab/db/models/projects.py
swanlab/log/__init__.py
swanlab/utils/__init__.py
swanlab/utils/file.py
test/unit/utils/pytest_file.py

* 更新项目名称不符合规范时的报错 close #512 
* 更新实验名称检查，优化代码
* 优化代码结构
* 增加单元测试
* 更改swanlab.login : 当用户未输入key时，则从本地寻找key进行登录，本地寻找key不存在时，要求登录

error tip when proj error

---

swanlab/api/upload/__init__.py
swanlab/api/upload/model.py
swanlab/cloud/_log_collector.py
test/create_error_chart.py

* 修复了错误图表时出现的409问题，可使用`test/create_error_chart.py`进行测试

fix api error

---

vue/src/charts/components/ExportImage.vue
vue/src/charts/package/LineChart.vue

修复因为 #534 更改样式后带来的折线图step没有对齐的问题，并且在导出折线图弹窗关闭时清空原始状态。

update linechart style

---

swanlab/data/callback_cloud.py
swanlab/package.json

install console

---

swanlab/api/auth/login.py
swanlab/data/callback_cloud.py
swanlab/env.py
swanlab/package.py
test/unit/auth/pytest_login.py
test/unit/conftest.py
test/unit/data/pytest_sdk.py
test/unit/pytest_env.py
tutils/__init__.py
tutils/config.py
tutils/utils.py

* 完善环境变量部分的单元测试
* 为单元测试编写一些hook，避免重复操作
* 完善登录的单元测试
为了实现单元测试，新增两个环境变量`SWANLAB_PACKAGE_PATH`和`SWANLAB_HOME`，前者设置swanlab包配置文件路径，后者设置.swanlab路径，都只有在开发模式生效
closes: #577

update env test

---

swanlab/data/system/info.py

PyNVML 旧版本的 nvmlDeviceGetName 可能会返回 bytes 类型，增加了对于类型的分析，如果出现 bytes 类型则进行 decode
Closes: #605

Fix nvmlDeviceGetName return type after-treatment

---

swanlab/api/upload/__init__.py
swanlab/data/callback_cloud.py
swanlab/data/run/callback/models/runtime.py
swanlab/data/run/callback/utils.py
swanlab/data/run/config.py
swanlab/data/run/main.py
swanlab/data/run/operator.py
test/unit/data/run/pytest_config.py

对config做了一些优化，并增加一些测试，包括如下内容：
> 以下设计基于用户不设置私有属性，也就是说无法通过`config.__a = 1`的方式设置配置，在python层面这就是不被推荐的
SwanLabConfig继承 `MutableMapping`，这意味着可以使用与字典相同的方式使用SwanLabConfig实例，并且增加以下内容：
1. 支持通过属性的方式设置和访问，类似：`config.a=1`与`config.a==1`——需要注意的是如果访问属性时不存在将报错，这与字典类似，并且不允许设置私有属性
2. SwanLabConfig实例化时可输入两个参数，分别是`config`和`on_setter`，config可支持MutableMapping，包括输入的是SwanLabConfig
4. 添加了与字典一样的get方法，可以设置默认值
5. 添加update方法，传入的对象必须是MutableMapping或者argparse.Namespace，也支持类似`update(a=1)`的方式设置——不过update只能覆盖，比如原本数据是`config.a={"b":1}`，此时设置`config.update(a={"c":1})`会变为`config.a={"c":1}`
6. 需要注意的是，处于性能考虑，如果是深层次的设置，例如`config.a["b"]`此时无法触发保存方法，这种情况推荐使用update方法
在实验开始前，可以通过`swanlab.config`访问、设置配置，当实验开始后，`run.config`和`swanlab.config`本质上指向同一个实例，因此对于其修改，本质上是对同一个实例的修改。
在实验结束后，swanlab.config被清空，`run.config`保留，但是run.config的设置将不再触发保存。 …

opt config

---

swanlab/data/run/system/info.py

1. "pid"：增加了对PID（进程号）的记录
2. "python_verbose"：增加了对Python详细版本信息的记录
```python
return {
"swanlab": {"version": version, "logdir": logdir},  # swanlab 版本号和日志目录
"hostname": socket.gethostname(),  # 主机名
"os": platform.platform(),  # 操作系统
"python": platform.python_version(),  # python版本
"python_verbose": sys.version,  # python详细版本
"executable": sys.executable,  # python 解释器路径
"git_remote": __get_remote_url(),  # 获取远程仓库的链接
"cpu": multiprocessing.cpu_count(),  # cpu 核心数
"gpu": __get_gpu_info(),  # gpu 相关信息
"git_info": __get_git_branch_and_commit(),  # git 分支和最新 commit 信息
"command": __get_command(),  # 完整命令行信息
"memory": __get_memory_size(),  # 内存大小
"cwd": __get_cwd(),  # 当前工作目录路径
"pid": os.getpid(),  # 当前进程ID
}
```

Feat/Env add PID and verbose Python version

---

swanlab/integration/mmengine.py
test/integration/mmengine/README.md
test/integration/mmengine/mmengine_train.py
test/integration/mmengine/mmengine_visualizer_import.py
test/integration/mmengine/requirements.txt

test script
Refer to [mmengine official document](https://mmengine.readthedocs.io/en/latest/get_started/installation.html).
Install the environment with following command.
```sh
pip install torch torchvision --index-url https://download.pytorch.org/whl/cu121
pip install -U openmim
mim install mmengine
pip install swanlab
```
just run and it will auto downlaod cifar10 datasets
```python
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
from torch.optim import SGD
from torch.utils.data import DataLoader
from mmengine.evaluator import BaseMetric
from mmengine.model import BaseModel
from mmengine.runner import Runner
from mmengine.visualization import Visualizer
from swanlab.integration.mmengine import SwanlabVisBackend
class MMResNet50(BaseModel): …
```

修复了mmengine集成中SwanlabVisBackend的save_dir不能为None的问题

---

requirements-dev.txt
swanlab/log/console.py
test/unit/log/pytest_log.py
tutils/__init__.py
tutils/check.py

解决了两个问题：
* 修复日志文件分片，新增加一个`freezegun`工具用于测试时的时间冻结
* 终端标准输出流编码问题，如果系统为gbk编码，输出类似emoji符号时将会报错，但此问题无法有效复现，正确的处理应该是用户设置`LANG=utf-8`环境变量，现在的处理是增加`UnicodeEncodeError`捕获，如果出错就pass
---
如果有比较详细的错误描述和复现流程会更好，但目前没有

fix sharding and encoding

---

swanlab/data/modules/audio/__init__.py
swanlab/data/modules/image/__init__.py

fix import

---

.vscode/launch.json
swanlab/data/formater.py
swanlab/data/run/main.py
test/unit/data/pytest_fomater.py

windows有保留文件夹名，参考https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN
```python
import swanlab
swanlab.init(project='test_swanlab')
for i in range(100):
swanlab.log({"test1":i})
swanlab.log({'AUX':i**2})
```
Close: #639

修复win环境下部分指标无法跟踪的问题

---

swanlab/integration/torchtune.py

与torchtune微调框架的集成，已在Gemma-2b模型微调上试验成功。
使用方法：
1. 安装torchtune：
```bash
pip install torchtune
```
2. 下载gemma-2b预训练模型到本地：
```python
from modelscope import snapshot_download
model_dir = snapshot_download('AI-ModelScope/gemma-2b', cache_dir="./",)
```
3. 创建`2B_qlora_single_device.yaml`：
```yaml
#
#
#
#
tokenizer:
_component_: torchtune.models.gemma.gemma_tokenizer
path: ./AI-ModelScope/gemma-2b/tokenizer.model
dataset:
_component_: torchtune.datasets.alpaca_dataset
seed: null
shuffle: True
model:
_component_: torchtune.models.gemma.qlora_gemma_2b
lora_attn_modules: ['q_proj', 'k_proj', 'v_proj']
apply_lora_to_mlp: True
lora_rank: 64
lora_alpha: 16
checkpointer:
_component_: torchtune.utils.FullModelHFCheckpointer
checkpoint_dir: ./AI-ModelScope/gemma-2b/
checkpoint_files: [ …
```

integration-torchtune

---

swanlab/data/run/system/info.py
swanlab/data/run/system/monitor.py

1. 使用pynvml.nvmlSystemGetDriverVersion()获取 NVIDIA 驱动版本信息
2. 使用subprocess.run(["conda",'list'], stdout=subprocess.PIPE, text=True)获取当前conda环境信息
3. 使用psutil.sensors_temperatures()获取当前系统所有传感器的温度
4. 使用psutil.cpu_freq(percpu=False)获取系统cpu的频率
https://github.com/SwanHubX/SwanLab/issues/666
https://github.com/SwanHubX/SwanLab/issues/136

support more info

---

requirements.txt

Added minimum version constraints for urllib3 and requests in requirements.txt. 
It is important to note that both the urllib3 and requests libraries are using **the oldest versions** that are free of bugs.
To resolve the "TypeError: __init__() got an unexpected keyword argument 'allowed_methods'" error and JSONDecodeError. The error occurred in a user environment running Ubuntu 20.04, where the user was using the system’s pre-installed Python 3.8.10, with older versions of the Requests and urllib3 libraries already installed in the environment.
Pass (In Ubuntu 20.04 + Python 3.8.10)

fix: add minimum version constraints for urllib3 and requests

---

swanlab/cli/commands/launcher/__init__.py
swanlab/cli/commands/launcher/parser/v1/folder.py
swanlab/data/formater.py

* 修复exclude没有生效的问题
* 修复windows的编码问题
* 完善错误提示

fix:encoding

---

.vscode/launch.json
requirements-dev.txt
swanlab/api/auth/login.py
swanlab/error.py
test/unit/api/auth/test_login.py
test/unit/cli/test_cli_login.py
test/unit/data/test_sdk.py

解决ISSUE #688 
1. 修复了在login之前没检查key格式的问题
2. 增加了windows粘贴提醒，以及key长度问题
3. 把一个跳过云的测试设置一起更新了
（PS，windows上还是没法跑全量测试 #650 ）
Close: #688

Fix win login error

---

swanlab/integration/huggingface.py
swanlab/integration/transformers.py
test/integration/huggingface/transformers_bert_train.py

改动：
1. 将integrate的方式由从`from swanlab.integration.huggingface import SwanLabCallback`改为了from swanlab.integration.transformers import SwanLabCallback。
2. 保留`from swanlab.integration.huggingface import SwanLabCallback`引入方式，但会报warning
3. 删除了对仅存在单次的标量的跟踪（如下图）
4. 在训练config记录中增加了对模型config的支持

Transformers integrate update

---

swanlab/data/run/exp.py
swanlab/data/run/helper.py
swanlab/data/run/main.py
swanlab/data/sdk.py

change:file name

---

.github/workflows/test-when-pr.yml
swanlab/data/run/namer.py
test/unit/data/run/test_namer.py

add:generate-color and name

---

swanlab/data/run/main.py
swanlab/data/run/system/info.py

refactor: linux cpu brand return

---

swanlab/data/run/main.py
swanlab/data/run/public.py
test/unit/data/test_sdk.py

`swanlab.init`返回的类`run`会携带`public`属性，替换了之前的`settings`属性，他会返回：
1. project_name 当前运行的项目名称
2. version 当前运行的swanlab版本
3. run_id 一个唯一id
4. swanlog_dir swanlab保存文件夹
5. run_dir 本次实验的保存文件夹
6. cloud 云端环境的相关信息
cloud信息包括：
1. avaliable 是否运行在云端模式，如果不是，下面的属性全部为`None`
2. project_name 本次运行的项目名称
3. project_url 本次运行在云端项目url
4. experiment_name 本次运行的实验名称
5. experiment_url 本次运行的云端实验url

replace settings to public

---

swanlab/data/run/metadata/hardware.py
swanlab/data/run/metadata/utils/ascend.py

昇腾NPU检测，以芯片为单位检测，目前只检测其驱动版本和容量
这块也没啥办法写单元测试...不过在顶层加了try-catch
close #739

feat: ascend npu detection

---

swanlab/integration/xgboost.py
test/integration/xgboost/train_xgboost.py

增加对XGBoost的集成，案例：
```python
import xgboost as xgb
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import swanlab
from swanlab.integration.xgboost import SwanLabCallback
swanlab.init(project="xgboost-breast-cancer", config={
"learning_rate": 0.1,
"max_depth": 3,
"subsample": 0.8,
"colsample_bytree": 0.8,
"num_round": 100
})
data = load_breast_cancer()
X = data.data
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)
params = {
'objective': 'binary:logistic',  # 二分类任务
'max_depth': 3,                  # 树的最大深度
'eta': 0.1, …
```

feat: integration xgboost

---

swanlab/integration/lightgbm.py
test/integration/lightgbm/train_lightgbm.py

测试代码：
```python
import lightgbm as lgb
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import swanlab
from swanlab.integration.lightgbm import SwanLabCallback
swanlab.init(project="lightgbm-example", name="breast-cancer-classification")
data = load_breast_cancer()
X = data.data
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
train_data = lgb.Dataset(X_train, label=y_train)
test_data = lgb.Dataset(X_test, label=y_test, reference=train_data)
params = {
'objective': 'binary',
'metric': 'binary_logloss',
'boosting_type': 'gbdt',
'num_leaves': 31,
'learning_rate': 0.05,
'feature_fraction': 0.9
}
num_round = 100
gbm = lgb.train(
params, …
```

feat: integration lightgbm

---

docs/硬件信息采集.md
requirements.txt
swanlab/data/run/main.py
swanlab/log/console.py
test/unit/log/test_log.py

* 更改psutil 版本
* 增大日志上传的一行最大字符 
close #304 
close #726

feat: increase log len

---

swanlab/data/run/metadata/hardware/gpu/nvidia.py
swanlab/data/run/metadata/hardware/type.py

* 在GPU检测时，部分机子可能出现GPU乱码的情况，此时忽略错误，但GPU硬件信息不再采集和监控
* 在硬件监控时，可能出现检测错误的情况，此时可能是GPU驱动过低、型号过于老旧等，原本设计是使用error的log，但是会影响用户体验，改为debug。
close #753

chore: fix some misc

---

swanlab/env.py

Add temporary domain `swanlab.115.zone`.  If the primary domain is broken, the temporary domain can be used.
Please include a concise summary, in clear English, of the changes in this pull request. If it closes an issue, please
mention it here.
Closes: #(issue)
Before your create a PR, please check to see if there is [an existing issue](https://github.com/SwanHubX/SwanLab/issues)
for this change. If not, please create an issue before you create this PR, unless the fix is very small.
Not adhering to this guideline will result in the PR being closed.

fix: temporary domain

---

swanlab/data/run/metadata/hardware/gpu/nvidia.py
swanlab/data/run/metadata/hardware/type.py
swanlab/data/sdk.py
test/unit/data/run/metadata/hardware/test_type.py

* 针对GPU部分添加包装器，为采集任务添加错误捕获，解决 一损俱损 的问题
* 优化了部分import的导入
close #773

feat: dynamic catch collect task error

---

swanlab/api/auth/login.py
swanlab/data/callback_cloud.py
swanlab/data/sdk.py
swanlab/env.py
swanlab/package.py
test/unit/data/test_sdk.py
test/unit/test_env.py
test/unit/test_package.py

* 优化了一些import导入
* 为 swanlab.init 在初始化时添加选择交互，并添加、修改了相关测试
close #632 
---
“选择交互”仅在程序连接标准输入时启用，在pycharm中不适用，但在jupyter中做了单独适配——这与原本的标准输出检测是类似的。
这样设计的目的是防止用户在使用脚本开启实验时出现的程序挂起情况。

feat: add choices for swanlab.init

---

README.md
README_EN.md
README_JP.md
README_RU.md

This pull request updates the links in multiple language versions of the `README` files to point to the correct demo charts for the audio classification and Qwen2-VL projects. The most important changes include updating the URLs for the demo links in the English, Japanese, and Russian `README` files.
Updates to demo links:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L395-R398): Updated the links for `demo-audio-classification` and `demo-qwen2-vl` to point to the correct charts.
* [`README_EN.md`](diffhunk://#diff-cd16b6fe8b71c753765db6d9a05343a02db0fd5f4e0fa195969d2b6f923505abL391-R394): Updated the links for `demo-audio-classification` and `demo-qwen2-vl` to point to the correct charts.
* …

fix: readme link

---

swanlab/sync/wandb.py

此拉取请求包括对`swanlab/sync/wandb.py`文件中的`sync_wandb`函数的更新，以增强其功能并改善与Swanlab和Weights & Biases（wandb）库的集成。这些更改引入了新参数、额外的日志记录功能以及更好的配置处理。
对`sync_wandb`函数的增强：
- 在`sync_wandb`函数中添加了`mode`和`wandb_run`参数，以便更好地控制同步模式以及是否应将数据上传到wandb。（`swanlab/sync/wandb.py`）
- 更新了`patched_init`函数，以包含新的`mode`参数并处理`wandb_run`设置，如果`wandb_run`设置为`False`，则允许离线模式。（`swanlab/sync/wandb.py`）
配置和日志记录改进：
- 引入了`patched_config_update`函数，以便在wandb的配置更新时更新Swanlab的配置。（`swanlab/sync/wandb.py`）
- 修补了wandb配置更新方法，以使用新的`patched_config_update`函数。（`swanlab/sync/wandb.py`）
Closes: #793

feat: sync wandb add params

---

swanlab/package.py
test/unit/test_package.py

This pull request includes several changes to the `swanlab/package.py` file and the associated unit tests to improve the handling of `.netrc` files and ensure that only one host entry is maintained. The most important changes include the addition of a new function to get the `.netrc` file path, updates to existing functions to use this new function, and enhancements to the unit tests to verify the new behavior.
* [`swanlab/package.py`](diffhunk://#diff-aabef23bd5d0551b5c6a89b2bd7745b1d3a612652f66946214a7fa16778c0db8R100-R106): Added a new function `get_nrc_path()` to obtain the `.netrc` file path.
* [`swanlab/package.py`](diffhunk://#diff-aabef23bd5d0551b5c6a89b2bd7745b1d3a612652f66946214a7fa16778c0db8L108-R115): Updated the `get_key()` and `save_key()` functions to use the new …

feat: only one api key

---

swanlab/sync/tensorboard.py
swanlab/sync/wandb.py
test/sync_tensorboardX.py
test/sync_tensorboard_torch.py
test/sync_wandb.py

This pull request includes several enhancements and refactorings to the `swanlab/sync` module, specifically targeting the tensorboard and wandb synchronization functionalities. The changes introduce a common utility function for extracting arguments and add support for additional tensorboard methods.
Enhancements to argument extraction:
* [`swanlab/sync/tensorboard.py`](diffhunk://#diff-dc24c28c4068c3d6a86656137e165ea9eeda9b299da3b7b4750148fa71062811R3-R22): Added `_extract_args` function to extract parameters from `args` and `kwargs` in a consistent manner.
* [`swanlab/sync/wandb.py`](diffhunk://#diff-e316aa53f23b70154cc8349bedbb5f045383a8e58bbc1acbd055d5e4fd251c83R3-R23): Added `_extract_args` function to extract parameters from `args` and `kwargs` in a consistent manner.
Enhancements …

feat: sync enhancement

---

swanlab/api/__init__.py
swanlab/api/auth/login.py
swanlab/api/http.py
swanlab/api/info.py
swanlab/cli/commands/auth/login.py
swanlab/cli/commands/auth/logout.py
swanlab/data/callback_cloud.py
swanlab/data/run/metadata/cooperation/__init__.py
swanlab/data/run/public.py
swanlab/data/sdk.py
swanlab/package.py
test/unit/api/auth/test_login.py
test/unit/test_package.py
tutils/setup.py

此拉取请求包含对`swanlab`模块的多项更改，主要集中在改进登录功能、URL处理和代码组织上。最重要的更改包括新增了用于处理URL的属性和方法、更新了登录机制，并进行了重构以提高代码清晰度。
主要是为 #792 的实现做准备。
* 在`swanlab/api/__init__.py`中添加了`is_login`函数，通过验证HTTP对象的存在来检查用户是否已登录。
* 更新了`swanlab/api/auth/login.py`中的`login_request`和`login_by_key`函数，使其接受并使用`api_host`和`web_host`参数。[[1]](diffhunk://#diff-2a5827973e640dc996618a75e9ff2f6e97ab778095647f13cd5a5de7e54fd516L23-R28) [[2]](diffhunk://#diff-2a5827973e640dc996618a75e9ff2f6e97ab778095647f13cd5a5de7e54fd516L45-R48)
* 在`swanlab/api/http.py`中引入了`base_url`、`api_host`、`web_host`、`web_proj_url`和`web_exp_url`属性，以便更好地管理URL。[[1]](diffhunk://#diff-59d6f0332f63c34567b4c6ad36216611d1ec51e7a6f6fc991c360a2736b3f4ecR70-R83) [[2]](diffhunk://#diff-59d6f0332f63c34567b4c6ad36216611d1ec51e7a6f6fc991c360a2736b3f4ecR125-R139)
* …

chore: add api and web host to http obj

---

swanlab/converter/__init__.py
swanlab/converter/tfb/_utils.py
swanlab/converter/wb/wb_converter.py

此前使用from swanlab.converter import WandbConverter会出现ModuleNotFoundError: No module named 'tensorflow'错误
现在使用延迟引入的方式按需导入WandbConverter或者TFBConverter

Implement lazy loading to avoid unnecessary imports

---

swanlab/data/run/main.py
test/unit/data/run/test_main.py

This pull request includes changes to the `swanlab/data/run/main.py` file to add support for logging nested dictionaries by flattening them. The most important changes include adding a helper method to flatten nested dictionaries, updating the `log` method to handle nested dictionaries, and modifying the key format check to work with the flattened dictionary.
Improvements to nested dictionary handling:
* [`swanlab/data/run/main.py`](diffhunk://#diff-716884b2803891f14f0e31a96ce3c380a52b38283304a509d29b4caa9d9abceaR312-R322): Added a helper method `__flatten_dict` to flatten nested dictionaries with dot notation.
* [`swanlab/data/run/main.py`](diffhunk://#diff-716884b2803891f14f0e31a96ce3c380a52b38283304a509d29b4caa9d9abceaL323-R335): Updated the `log` method to accept nested dictionaries …

feat: support nest log

---

docs/登录认证.md
swanlab/api/info.py
swanlab/data/sdk.py
swanlab/env.py
swanlab/package.py
test/unit/data/test_sdk.py
test/unit/test_env.py
test/unit/test_package.py

本次 Pull Request 包括多项更改，以优化登录认证流程并增强 SwanLab SDK 中主机格式处理的功能。主要更新包括登录逻辑改进 #792  、引入新的 `HostFormatter` 类以及环境变量处理的调整。
- [`docs/登录认证.md`](diffhunk://#diff-317dd29f5bd964830f571905f1f7df09f9504b6c5468b4343ef84dd6fda1f9f1R1-R7)：新增登录认证文档，并提供相关问题链接以供进一步探索。  
- [`swanlab/api/info.py`](diffhunk://#diff-b18458402c6b61bc7e67220fca1bf765070faf743bcaa788b95d0638f5843c00L14-R14)：更新 `LoginInfo` 类，使用新的 `fmt_web_host` 函数进行 Web 主机格式化，并修改 `save` 方法以保存 Web 主机和 API 主机信息。  
- [`swanlab/data/sdk.py`](diffhunk://#diff-158dd8e86f8747fb6fb7b53a3880d678a4916f8b149dc71571ebe6372f300327R11)：引入 `HostFormatter` 类，以标准化主机 URL 格式，并更新登录函数以使用该格式器验证并设置主机环境变量。  
- [`swanlab/env.py`](diffhunk://#diff-5fe153a98ec08bba37a638f14053c3cd60760fee2cb2fc5b0d2b206f0f0f84e4R12-R14)：为 `SwanLabEnv` 类新增方法，以验证字符串是否为有效主机名，并更新 `set_default` …

feat: login with host

---

swanlab/cli/commands/auth/login.py
swanlab/data/sdk.py
swanlab/env.py
swanlab/package.py
test/unit/cli/test_cli_login.py
test/unit/data/test_sdk.py
test/unit/test_package.py

该拉取请求（Pull Request）对 `swanlab` 项目进行了重要更新，重点涉及 `HostFormatter` 类及其在多个模块中的集成。主要改动包括 `HostFormatter` 类的迁移与增强、登录功能的更新，以及额外的测试以确保系统的健壮性。
* `HostFormatter` 类已从 `swanlab/data/sdk.py` 移动到 `swanlab/package.py`，并增强了对 `host` 和 `web_host` 参数的处理能力。该类现在负责验证和格式化主机 URL，并设置相关的环境变量。[[1]](diffhunk://#diff-158dd8e86f8747fb6fb7b53a3880d678a4916f8b149dc71571ebe6372f300327L61-L85) [[2]](diffhunk://#diff-aabef23bd5d0551b5c6a89b2bd7745b1d3a612652f66946214a7fa16778c0db8R58-R101)
* 更新了 `swanlab/cli/commands/auth/login.py` 中的 `login` 函数，新增 `host` 和 `web_host` 选项，允许用户在登录时指定服务器和 Web 主机。
* 在重新登录时新增逻辑以清除环境变量，并使用 `HostFormatter` 类进行主机地址的验证和格式化。
* 移除了 `swanlab/data/sdk.py` 中冗余的 `HostFormatter` 类定义，并更新 `login` 函数以使用 `swanlab/package.py` 中的新 `HostFormatter` 类。[[1]](diffhunk://#diff-158dd8e86f8747fb6fb7b53a3880d678a4916f8b149 …

feat: host params for login cli

---

swanlab/data/run/metadata/hardware/cpu.py

- 在部分中文环境下的 bash 中，`lscpu` 无法正常读取到 cpu brand，这里替换成了直接去 /proc 中读
- 测试：

fix: cat /proc/cpuinfo

---

README.md
README_EN.md
README_JP.md
README_RU.md

更新了徽章，与assets仓库的引导链接
This pull request includes updates to the `README` files in multiple languages to replace the `swanlab-cloud-shield` badge with the `tracking-swanlab-shield` badge and to add new badges for visualizing SwanLab. Additionally, it removes the section for downloading the SwanLab icon and adds links to design materials.
Badge updates:
* Replaced `swanlab-cloud-shield` with `tracking-swanlab-shield` across all `README` files. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L21-R28) [[2]](diffhunk://#diff-cd16b6fe8b71c753765db6d9a05343a02db0fd5f4e0fa195969d2b6f923505abL21-R21) [[3]](diffhunk://#diff-3629b3e65246c37e96658c8e152222668d9313279ba005aee3f37b2c2afeef25L22-R22) [[4]](diffhunk://#diff-60c6c6575afc9f0439fc54f56d4d2814b6242d34d817 …

docs: readme badge

---

swanlab/__init__.py
swanlab/data/__init__.py
swanlab/data/run/__init__.py
swanlab/data/run/main.py
swanlab/log/console.py
test/unit/data/run/test_main.py
test/unit/data/test_sdk.py

这段拉取请求包括对`swanlab`包的几项更改，以增加新功能和改善代码组织。最重要的更改包括添加新函数以检索URL，重新组织导入，以及增强错误处理和测试。
* 在`swanlab/data/run/main.py`中添加了`get_url()`和`get_project_url()`函数，分别用于检索当前实验和项目的URL。
* 在`swanlab/__init__.py`和`swanlab/data/__init__.py`中重新组织了导入，包括`config`，`get_url`和`get_project_url`。[[1]](diffhunk://#diff-efa5d30597fa2ff8419efa65d5225bc4a5b86483333f4e43bd08edc5a37d3640R14-R19) [[2]](diffhunk://#diff-7ccd7e0b5499fb7aabef90fde0a625461376cad79d2f7aa3052d5094f13e1e87L15-R28)
* 更新了`swanlab/data/run/__init__.py`中的导入语句，以包含新函数。
* 在`swanlab/log/console.py`中增强了错误处理，以捕获在关闭的文件上尝试进行I/O操作时的`ValueError`。
* 在`test/unit/data/run/test_main.py`中为`get_url()`和`get_project_url()`函数添加了单元测试。[[1]](diffhunk://#diff-e448823e4559913f29ee14a5cdee9b99576080f5dde72cf7fef270c9bdee29d8R20-R24) …

feat: add some func for get exp info

---

swanlab/data/run/metadata/hardware/cpu.py
test/unit/data/run/metadata/hardware/gpu/test_nvidia.py
test/unit/data/run/metadata/hardware/test_cpu.py

- 在 EulerOS 上 `cat /proc/cpuinfo` 没有 model name... 需要跟 `lscpu` merge 一下
- ~~考虑到 locale 问题，subprocess 子进程中临时使用 `en_US.UTF-8`，防止中文 bash 影响~~ （没用，写在 `/usr/bin` 里救不了）
- fix：test_nvidia.py 成员函数引错导致单测没通过

fix(test): merge  lscpu

---

requirements.txt
swanlab/api/upload/__init__.py
swanlab/api/upload/model.py
swanlab/data/callback_cloud.py
swanlab/data/run/main.py
swanlab/data/run/metadata/__init__.py
swanlab/data/run/metadata/conda.py
test/unit/api/upload/test_model.py
test/unit/data/run/metadata/hardware/test_conda.py

此次拉取请求（Pull Request）为 `swanlab` 项目引入了多项更改，主要集中在添加对捕获和处理 Conda 环境信息的支持。这些更改涉及多个文件，包括模型更新、元数据处理以及单元测试。
主要更改包括：
* 在 `swanlab/api/upload/model.py` 中的 `FileModel` 类中添加了一个新的 `conda` 属性，并更新了 `create` 方法以处理这个新属性。[[1]](diffhunk://#diff-2c4391382afbb16619bb2524a64d44751f6eea5c9ddc344038b95759a331f8f9L189-L197) [[2]](diffhunk://#diff-2c4391382afbb16619bb2524a64d44751f6eea5c9ddc344038b95759a331f8f9L206-R224)
* 更新了 `swanlab/data/callback_cloud.py` 中的 `on_runtime_info_update` 方法，使其在创建 `FileModel` 实例时包含 Conda 信息。
* 修改了 `swanlab/data/run/main.py`，以导入并使用新的 `get_conda` 函数来获取 Conda 信息。[[1]](diffhunk://#diff-716884b2803891f14f0e31a96ce3c380a52b38283304a509d29b4caa9d9abceaR25) [[2]](diffhunk://#diff-716884b2803891f14f0e31a96ce3c380a52b38283304a509d29b4caa9d9abceaR129)
* 更新了 …

feat: conda env

---

swanlab/converter/wb/wb_converter.py

1. Adapt to the API format of the new wandb version
2. Might solve part of issue #852 :)
---
This pull request includes changes to the `parse_wandb_logs` method in the `swanlab/converter/wb/wb_converter.py` file. The updates focus on improving error handling and enhancing the processing of Wandb logs. The most important changes are:
Error handling improvements:
* Added a check to ensure `pandas` is installed when processing Wandb logs, raising a `TypeError` if it is missing.
* Wrapped the metadata extraction in a try-except block to handle potential errors gracefully.
Enhancements to Wandb log processing:
* Modified the assignment of the `cloud` parameter to simplify the configuration.
* Updated the logic to check if the history is a `DataFrame` and extract keys accordingly, improving …

fix: wandb conver

---

swanlab/data/run/metadata/runtime.py
test/unit/data/run/metadata/test_runtime.py

修复了在带端口号的http git链接下，会把端口号的冒号替换成'/'的问题
This pull request includes changes to the `get_remote_url` function in the `swanlab/data/run/metadata/runtime.py` file to improve URL handling for git repositories. The most important changes include modifying the URL conversion logic and updating the `replace_second_colon` function.
Improvements to URL handling:
* [`swanlab/data/run/metadata/runtime.py`](diffhunk://#diff-a66e7f50fd6bebdc5d3832d7405fd0b26c0550189a97c775f6ea9c6f5bed7ee7L68-R84): Modified the `get_remote_url` function to convert SSH URLs to HTTPS and remove the `.git` suffix without calling `replace_second_colon` unnecessarily.
* [`swanlab/data/run/metadata/runtime.py`](diffhunk://#diff-a66e7f50fd6bebdc5d3832d7405fd0b26c0550189a97c775f6ea9c6f5bed7ee7L68-R84): Updated the …

fix: port number git remote link

---

requirements-dashboard.txt
requirements.txt
swanlab/data/callbacker/cloud.py
swanlab/data/callbacker/local.py
swanlab/data/run/helper.py
swanlab/data/run/main.py

This pull request includes updates to the `swanlab` project, focusing on enhancing the flexibility of various callback methods by adding support for additional arguments. Additionally, there is a minor update to the `swanboard` dependency version.
Enhancements to callback methods:
* [`swanlab/data/callbacker/cloud.py`](diffhunk://#diff-733d6742a0ed52a329f3872a2f17de48637ce80a1af7f2a7a41a975d1d858972L103-R103): Updated several methods (`on_init`, `before_run`, `on_run`, `on_runtime_info_update`, `on_column_create`, `on_metric_create`, `on_stop`) to accept additional arguments (`*args, **kwargs`). [[1]](diffhunk://#diff-733d6742a0ed52a329f3872a2f17de48637ce80a1af7f2a7a41a975d1d858972L103-R103) [[2]](diffhunk://#diff-733d6742a0ed52a329f3872a2f17de48637ce80a1af7f2a7a41a975d1d858972L113-R116) …

feat: add args for callback

---

README.md
README_EN.md
README_JP.md
README_RU.md
swanlab/data/callbacker/local.py

This pull request includes updates to the `README` files in multiple languages to add instructions for installing the dashboard extension.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R197-R207): Added a section with instructions for installing the dashboard extension and a link to the relevant documentation.
* [`README_EN.md`](diffhunk://#diff-cd16b6fe8b71c753765db6d9a05343a02db0fd5f4e0fa195969d2b6f923505abR190-R199): Added a section with instructions for installing the dashboard extension and a link to the relevant documentation.
* [`README_JP.md`](diffhunk://#diff-3629b3e65246c37e96658c8e152222668d9313279ba005aee3f37b2c2afeef25R192-R201): Added a section with instructions for installing the dashboard extension …

docs: dashboard install

---

swanlab/data/run/metadata/hardware/gpu/nvidia.py

This pull request includes updates to the `swanlab/data/run/metadata/hardware/gpu/nvidia.py` file to enhance the functionality of the `get_nvidia_gpu_info` function. The key changes involve adding support for retrieving GPU architecture and CUDA core count information.
Enhancements to GPU information retrieval:
* Added a dictionary `NVIDIA_GPU_ARCHITECTURE` to map NVIDIA GPU architecture codes to their respective architecture names.
* Updated the `info` dictionary in the `get_nvidia_gpu_info` function to include `architecture` and `cudacores` fields.
* Modified the `get_nvidia_gpu_info` function to retrieve and append GPU architecture and CUDA core count information to the `info` dictionary.

feat: env add gpu nvidia architecture and cudacores

---

test/metrics/object3d.spatiallm.example.py

This pull request adds an example script demonstrating how to log point clouds and bounding boxes from the SpatialLM-Testset using SwanLab's 3D object logging capabilities.  This example provides a clear illustration of how to use the `Object3D` logging functionality within SwanLab for visualizing and tracking 3D data.

feat: Add Object3D spatiallm example

---

swanlab/data/modules/object3d/object3d.py

Replaced `Dict` with `dict` where `dict` is the intended runtime type and `Dict` is a typing hint. This resolves an issue with type interception and ensures accurate type handling.
```python
Object3D({"points":..., "boxes": ...})  # Dict cannot intercept this data
```

Fix: Change Dict to dict in _TYPE_HANDLERS type hints

---

swanlab/plugin/notification.py

- 添加针对 `Discord` 和 `Slack` 的 webhook callback 支持，无需 `secrets`，_务必保管好自己的 `webhook_url`以避免信息轰炸_
- 扩展：根据 `swanlab/plugin/notification.py` 中 `WebhookCallback` 的抽象基类，任意支持 webhook 功能的IM均可继承，只需要编写不到5行 `Bot` 和 `send_msg` 逻辑即可；
- Discord Demo
- Slack Demo
关联ISSUE： #909

feat(plugin): support extra discord & slack callback

---

swanlab/api/http.py
swanlab/data/sdk.py
swanlab/data/utils.py
swanlab/env.py
test/unit/data/test_sdk.py

新增 `SWANLAB_EXP_NAME` `SWANLAB_WORKSPACE` `SWANLAB_PROJ_NAME`三个环境变量 用于初始化时的参数传递
closes https://github.com/SwanHubX/SwanLab/issues/902

feat: new env

---

swanlab/data/modules/object3d/object3d.py
swanlab/data/modules/object3d/point_cloud.py

This pull request introduces a refactor to replace direct references to `np.ndarray` with a more flexible alias, `ndarray`, in the `Object3D` and `PointCloud` modules. This change improves maintainability and consistency when handling the optional dependency on NumPy. Additionally, minor formatting adjustments were made to clean up the code.
* Introduced `ndarray` as an alias for `np.ndarray` in both `object3d.py` and `point_cloud.py`, with fallback to `None` if NumPy is not installed. This ensures better handling of the optional dependency. (`[[1]](diffhunk://#diff-3874055d997b8d0ed7d6824eea827e06d0c153a4b59fcd0030088b6f3bb5316eR13-R19)`, `[[2]](diffhunk://#diff-3612ea6db2beba642c364af801265e0c34db777d5b5149c0d85636de614bd726R47-R51)`)
* Updated type annotations and type checks in …

fix: object3d import error

---

swanlab/api/upload/__init__.py

Limit the maximum concurrency from 3000 to 100 (the backend may not handle it).

chore: change (max columns)/req

---

swanlab/data/run/metadata/requirements.py
test/unit/data/run/metadata/test_requirements.py

This pull request modifies the `get_requirements` function in `swanlab/data/run/metadata/requirements.py` to improve error handling and streamline the logic for retrieving the list of installed Python packages. The most important changes include raising a specific exception when the `uv` command is not found and removing the generic exception handling.
Improvements to error handling:
* The function now raises a `FileNotFoundError` with a clear error message ("uv command run failed") if the `uv` command is not available, instead of silently falling back to `pip`.
Code simplification:
* Removed the generic `Exception` handling block, making the code more explicit and easier to debug.

fix: can not get pip list

---

swanlab/api/upload/__init__.py
swanlab/swanlab_settings.py

This pull request refactors the column upload functionality and adjusts the default settings for log uploads. The most important changes include simplifying the `upload_column` method to remove batch processing and introducing error handling for individual column uploads. Additionally, the default log upload interval has been reduced.
Due to some issues with the upload column interface, temporarily rolled back to #953.
* [`swanlab/api/upload/__init__.py`](diffhunk://#diff-7eef39be6eb534f3b784e5d8b8a0ea5882cc017cdc756d4c3ccfb01dde50ec9fR12): Removed the `MAX_COLUMNS_LENGTH` constant and the logic for splitting columns into batches. The `upload_column` method now uploads each column individually with error handling using the newly imported `ApiError` class. A warning comment has also been …

chore: revert upload column (#953)

---

docs/开放API.md
swanlab/__init__.py
swanlab/api/openapi/__init__.py
swanlab/api/openapi/base.py
swanlab/api/openapi/experiment.py
swanlab/api/openapi/group.py
swanlab/api/openapi/main.py
swanlab/api/openapi/project.py
test/unit/api/openapi/test_group.py

实现`OpenAPI`功能, 添加第一个开放API: `list_workspaces()`
```python
from swanlab import OpenApi
my_api = OpenApi()
my_workspaces = my_api.list_workspaces()
other_api = OpenApi(key='other_api_key')
print(other_api.list_workspaces())
```
可得到`my_workspaces`(Python列表)
```text
[{
'name': 'workspace1',
'username': 'kites-test3',
'role': 'OWNER'
},
{
'name': 'hello-openapi',
'username': 'kites-test2',
'role': 'MEMBER'
},
...
]
```
- 如果显式提供`key`, 则使用该`key`进行认证
- 否则开放API的认证与`swanlab.init()`的认证逻辑一致, 即
- 曾在终端登录过
- 显式使用`swanlab.login()`登录
https://github.com/SwanHubX/SwanLab/issues/960#issue-3031431009

feat(openapi): list workspaces

---

.gitignore
swanlab/api/openapi/base.py
swanlab/api/openapi/experiment.py
swanlab/api/openapi/group.py
swanlab/api/openapi/main.py
test/unit/api/openapi/test_experiment.py
test/unit/api/openapi/test_group.py

通过 OpenAPI 开放获取实验信息接口。
1. 该方法所需用户指定的参数有项目名称与实验唯一 cuid (目前 cuid 只能从前端的 url 中拿到)
3. 该方法输出包含如下参数：
```python
"""
Args:
project (str): 项目名
exp_cuid (str): 实验id
username (Optional[str]): 工作空间名, 默认为用户个人空间
Returns:
dict: 实验信息的字典, 包含以下字段:
- cuid (str): 实验的唯一标识符
- name (str): 实验名称
- description (str): 实验描述
- state (str): 实验状态, 为 'FINISHED' 或 'RUNNING'
- createdAt (str): 实验创建时间, 格式如 '2024-11-23T12:28:04.286Z'
- finishedAt (str): 实验完成时间（若有）, 格式如 '2024-11-23T12:28:04.286Z'
- profile (dict): 实验配置文件, 包含以下字段:
- config (dict): 实验的配置参数
- metadata (dict): 实验的元数据
- requirements (str): 实验的依赖项
- conda (str): 实验的 Conda 环境信息
若请求失败, 将返回包含以下字段的字典:
- code (int): HTTP 错误代码
- message (str): 错误信息
"""
```

feature: get experiment

---

swanlab/api/openapi/base.py
swanlab/api/openapi/experiment.py
swanlab/api/openapi/main.py
test/unit/api/openapi/test_experiment.py

获取项目下的实验列表(分页)
Args:
project (str): 项目名
username (Optional[str]): 工作空间名, 默认为用户个人空间
page (int): 页码, 默认为1
size (int): 每页大小, 默认为10
Returns:
dict: 实验列表分页信息的字典, 包含以下字段:
- total (int): 实验总数
- exps (list[dict]): 实验列表, 每个实验包含以下字段:
- cuid (str): 实验cuid
- name (str): 实验名称
- description (str): 实验描述
- state (str): 实验状态, 为 'FINISHED' 或 'RUNNING'
- show (bool): 显示状态
- createdAt (str): 创建时间, 格式如 '2024-11-23T12:28:04.286Z'
- finishedAt (str): 完成时间（若有）, 格式同上
- user (dict): 实验创建者的 'username' 与 'name'
- profile (dict): 实验配置文件, 包含以下字段:
- config (dict): 实验的配置参数
- metadata (dict): 实验的元数据
- requirements (str): 实验的依赖项
- conda (str): 实验的 Conda 环境信息
若请求失败, 将返回包含以下字段的字典:
- code (int): HTTP 错误代码
- message (str): 错误信息

feat(openapi): get project exps

---

swanlab/api/openapi/base.py
swanlab/api/openapi/experiment.py
swanlab/api/openapi/group.py
swanlab/api/openapi/main.py
swanlab/api/openapi/types.py
test/unit/api/openapi/test_experiment.py
test/unit/api/openapi/test_group.py

为 OpenApi 某些复杂响应添加类型约束, 取代原先的长篇注释, 对IDE提示更友好
现:
```python
from swanlab.api.openapi.types import Experiment, ApiErrorResponse
def get_project_exps(
self,
project: str,
page: int = 1,
size: int = 10,
username: Optional[str] = None
) -> tuple[list[Experiment], int] | ApiErrorResponse:
"""
获取项目下的实验列表(分页)
Args:
project (str): 项目名
username (Optional[str]): 工作空间名, 默认为用户个人空间
page (int): 页码, 默认为1
size (int): 每页大小, 默认为10
Returns:
tuple[list[Experiment], int] | ApiErrorResponse:
- tuple[list[Experiment], int]:
- list[Experiment]: 实验列表, 每个实验的字典包含实验信息
- int: 实验总数
- ApiErrorResponse: 若请求失败, 返回此包含以下字段的字典:
- code (int): HTTP错误码
- message (str): 错误信息
"""
return self.experiment.get_project_exps(
username=username if username else self.http.username,
projname=project,
page=page,
size=size
)
```
原:
```python …
```

feat(openapi): types

---

swanlab/api/openapi/base.py
swanlab/api/openapi/experiment.py
swanlab/api/openapi/main.py
swanlab/api/openapi/project.py
swanlab/api/openapi/types.py
test/unit/api/openapi/test_experiment.py
test/unit/api/openapi/test_group.py
test/unit/api/openapi/test_project.py

- API 文档：https://github.com/SwanHubX/SwanLab-Server/blob/main/docs/api/project.md#%E5%88%97%E5%87%BA%E7%BB%84%E7%BB%87%E6%89%80%E6%9C%89%E9%A1%B9%E7%9B%AE
```
列出一个 workspace 下的所有项目
Args:
username (str): 工作空间名, 默认为用户个人空间
detail (bool): 是否包含项目下实验的相关信息，默认为 True
page (int): 页码, 默认为 1
size (int): 每页大小, 默认为 20
Returns:
dict: 项目列表信息的字典, 包含以下字段:
- code (int): HTTP 错误代码
- errmsg (str): 错误信息, 仅在请求有错误时非空
- data (Pagination[Project]): 项目列表, 包含以下字段:
- total (int): 指定工作空间下的项目总数
- list (list[Project]): 项目列表, 每个元素都是项目信息的字典, 包含项目信息 （list 长度与 p对应page页的size 一致）
Project 包括如下字段信息:
- cuid (str): 项目的唯一标识符
- name (str): 项目名称
- description (str): 项目描述
- visibility (str): 项目可见性, 如 'PUBLIC' 或 'PRIVATE'
- createdAt (str): 项目创建时间, 格式如 '2025-01-06T14:25:29.075Z'
- updatedAt (str): 项目更新时间, 格式如 …
```

feat(openapi): list projects

---

swanlab/api/upload/__init__.py
swanlab/data/cloud/task_types.py
swanlab/swanlab_settings.py

This pull request introduces a batch processing mechanism for column uploads, updates related references, and adjusts a default setting for log uploads. The most important changes are grouped and summarized below:
* Modified `upload_column` to `upload_columns` in `swanlab/api/upload/__init__.py`, enabling batch uploads with a configurable maximum length per request (`per_request_len`). Columns are split into smaller lists and uploaded sequentially.
* Updated the `UploadType.COLUMN` configuration in `swanlab/data/cloud/task_types.py` to reference the new `upload_columns` function.
* Removed the unused `ApiError` import from `swanlab/api/upload/__init__.py`.
* Changed the default `upload_interval` in `swanlab/swanlab_settings.py` from 1 second to 3 seconds, increasing the interval between …

chore: revert upload column again

---

swanlab/api/openapi/experiment.py
swanlab/api/openapi/types.py
test/unit/api/openapi/test_types.py

This PR enhances the usability of OpenAPI response objects by allowing both attribute-style and dictionary-style access.
Support accessing OpenAPI response object fields via:
- obj.name
- obj.get("name")
- obj["name"]
> ⚠️ Note: The object supports dict-style access but is not a real dictionary.
> To get the actual dictionary representation, use obj.model_dump().
- Fixed a type error encountered during model conversion when using pydantic models.
---
Closes: #976

feat(openapi): support dict-style access for object

---

swanlab/api/http.py
swanlab/data/run/metadata/runtime.py
swanlab/swanlab_settings.py
test/unit/data/run/metadata/test_runtime.py

添加 `swanlab.Settings` 字段 `security_mask`，用以替换隐私信息，如启动命令中的 api key。`security_mask` 默认启用。
Closes: #970

feat: security mask

---

swanlab/api/http.py
swanlab/api/upload/__init__.py

This pull request introduces improvements to the HTTP handling and error management in the `swanlab` API, including enhanced type annotations, better error handling for specific cases, and the addition of a new utility function. The most important changes are grouped below:
* Updated the `post` method in `swanlab/api/http.py` to accept both dictionaries and lists as valid types for the `data` parameter, improving flexibility in HTTP requests. (`[swanlab/api/http.pyL179-R179](diffhunk://#diff-59d6f0332f63c34567b4c6ad36216611d1ec51e7a6f6fc991c360a2736b3f4ecL179-R179)`)
* Enhanced the `upload_columns` function in `swanlab/api/upload/__init__.py` to handle `ApiError` exceptions. Specifically, it now logs a warning and skips uploading columns if the resource is disabled (HTTP 404 with a …

fix: resend request when experiment does not exist

---

swanlab/data/run/main.py

This PR fix a bug from #988 , now only `all` and `stderr` can upload error info

fix: only all and stderr can upload error info

---

swanlab/integration/accelerate.py

更新了accelerate tracker集成的实现，并且也同步给huggingface accelerate 提交了集成[PR](https://github.com/huggingface/accelerate/pull/3605) 
Closes: #1014 
--
**步骤 0：设置 Accelerate 和示例环境**
按照 **accelerate** 官方的计算机视觉示例（宠物图像分类任务）：
```bash
git clone https://github.com/huggingface/accelerate  
cd accelerate
pip install -e .
pip install timm     # 示例中使用
```
**步骤 1：设置 SwanLab 在线追踪**
安装：
```bash
pip install swanlab
```
要使用 SwanLab 的在线追踪功能，请登录 [SwanLab 网站](https://swanlab.cn/)，并从 [设置页面](https://swanlab.cn/space/~/settings) 获取你的 API 密钥。然后使用以下命令进行身份验证：
```bash
swanlab login
```
如果你更喜欢离线模式，请跳过此步骤并安装本地仪表板：
```bash
pip install swanlab[dashboard]
```
**步骤 2：下载示例代码中使用的 *Oxford-IIT Pet Dataset***
你可以在这里找到下载链接 [here](https://www.robots.ox.ac.uk/~vgg/data/pets/)  
**步骤 3：运行 Accelerate 项目中的官方示例脚本**
```bash
python …
```

update SwanLabTracker for accelerate

---

swanlab/data/run/metadata/hardware/__init__.py
swanlab/data/run/metadata/hardware/dcu/hygon.py
swanlab/data/run/metadata/hardware/gpu/moorethreads.py

> 海光 DCU 同样支持 `json` 格式输出指标 （不过会有一些奇怪的尖刺...），基本用法：`hy-smi --showxxx --json`
- 支持海光 DCU 硬件信息指标监控
- 设计文档：https://rjwalmzfj2.feishu.cn/docx/CvBcdTrMnokb9YxI2AocHKUEnRg?from=from_copylink
- 更正摩尔线程 `Moore Threads` 的命名

feat: support DCU monitor

---

swanlab/data/run/metadata/hardware/npu/ascend.py

This pull request enhances the `ascend.py` file by adding functionality to monitor NPU power usage. The changes include updates to the initialization method, a new method for retrieving power metrics, and integration of power data collection into the existing workflow.
* **Initialization of power monitoring configurations**:
- Added `self.power_key` for generating unique keys for NPU power metrics.
- Introduced `power_config` and `self.per_power_config` to store chart configurations for power usage.
- Updated the initialization loop to clone power configurations for each NPU chip.
* **New method for power data retrieval**:
- Added `get_chip_power` method to fetch power usage data using the `npu-smi` command and format it into the required hardware info structure.
* **Integration of power …

feat: allow get npu power

---

swanlab/cli/commands/ sync/__init__.py
swanlab/data/callbacker/backup.py
swanlab/log/backup/__init__.py
swanlab/log/backup/datastore.py
swanlab/log/backup/handler.py
swanlab/log/backup/models.py
test/unit/log/backup/test_datastore.py

借鉴 W&B 的本地日志保存方案，使用 Google 的 LevelDB 协议保存持久化数据并实现完整性校验，防止数据损坏和篡改

feat: leveldb

---

requirements.txt
swanlab/data/callbacker/backup.py
swanlab/data/run/main.py
swanlab/data/sdk.py
swanlab/data/utils.py
swanlab/env.py
test/unit/data/test_sdk.py
tutils/__init__.py

Change backup mode to offline and fix https://github.com/SwanHubX/SwanLab/issues/1033

refactor: change backup mode to offline

---

swanlab/integration/xgboost.py

Add a feature importance chart, using the characteristics of ECharts.

feat: update xgboost integration

---

swanlab/integration/accelerate.py

感谢社区用户@Laniakea 报bug
在使用accelerate 1.7.0及以下版本会出现无法正确初始化swanlab的问题
具体表现是
```bash
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/chenshaohon/projects/accelerate/examples/complete_cv_example.py", line 331, in <module>
[rank0]:     main()
[rank0]:   File "/home/chenshaohon/projects/accelerate/examples/complete_cv_example.py", line 327, in main
[rank0]:     training_function(config, args)
[rank0]:   File "/home/chenshaohon/projects/accelerate/examples/complete_cv_example.py", line 260, in training_function
[rank0]:     accelerator.log(
[rank0]:   File "/home/chenshaohon/miniconda3/envs/acc_itg/lib/python3.12/site-packages/accelerate/accelerator.py", line 787, in _inner
[rank0]:     return PartialState().on_main_process(function)(*args, **kwargs)
[rank0]: …
```

修复SwanLab accelerate集成使其对1.7.0版本及以下accelerate支持

---

swanlab/data/run/metadata/hardware/dcu/hygon.py
swanlab/data/run/metadata/hardware/gpu/metax.py
swanlab/data/run/metadata/hardware/gpu/moorethreads.py
swanlab/data/run/metadata/hardware/mlu/cambricon.py
swanlab/data/run/metadata/hardware/npu/ascend.py
test/unit/data/run/metadata/hardware/dcu/test_hygon.py
test/unit/data/run/metadata/hardware/gpu/test_metax.py
test/unit/data/run/metadata/hardware/gpu/test_moorethreads.py
test/unit/data/run/metadata/hardware/mlu/test_cambricon.py
test/unit/data/run/metadata/hardware/npu/test_ascend.py

显存使用量 metric 记录
- 昇腾 NPU：
https://swanlab.cn/@nexisato/Ascend-NPU-Metric-Demo/runs/sdqgqvtj8bdeo5yphlei4/system
- 沐曦 GPU：
https://swanlab.cn/@nexisato/qwen3-sft-medical/runs/94g0fzzaxan8ut7pj5dv3/system
- 海光 DCU：（icon 需要适配）
https://dev001.swanlab.cn/@nexisato/Hygon-DCU-Metric-Demo/runs/341w9qoipzuo0xivkwscd/system
- 寒武纪 MLU：
https://dev001.swanlab.cn/@nexisato/Cambricon-MLU-Metric-Demo/runs/xpi0iahiv8qs6k1lww7zv/system
- 摩尔线程 GPU：
https://swanlab.cn/@nexisato/MUSA-Project-Demo/runs/er903lsdq794gmh2i86xh/system
Issue: #1042

feat: support memory record

---

requirements.txt

测试发现requests在`2.26.0`之前无法导出`JSONDecodeError`，因此更新requests的限制为 `>=2.28.0`
> 提高两个版本也没啥问题 : )

fix: requests version

---

swanlab/plugin/__init___.py
swanlab/plugin/writer.py

增加1个插件`LogdirFileWriter`，它的作用是：支持传入1个文件路径列表，会在执行`swanlab.init`时，将文件移动到对应的`run`文件夹下
参数：
- `sub_dir`：如果不为None，则在`run`目录下创建1个sub_dir文件夹来保存文件
- `file_path`：支持传入1个文件路径列表（也支持仅传入1个str）
Related Issue: #1106 
测试代码：
```python
from swanlab.plugin.writer import LogdirConfigWriter
import swanlab
logdir_config_writer = LogdirConfigWriter(
sub_dir="code",
file_path=["a.py", "b.py"],
)
swanlab.register_callbacks([logdir_config_writer])
swanlab.init()
```

feat: LogdirFileWriter plugin

---

swanlab/api/base.py
swanlab/api/experiment.py
swanlab/api/main.py
swanlab/api/project.py
test/unit/api/test_experiment.py
test/unit/api/test_project.py

Add DELETE APIs for projects and experiments
```python
res = api.delete_project(
username=username,
project=project
)
```
res.code = 204 if project was deleted successfully
```python
res = api.delete_experiment(
username=username,
project=project,
exp_id=cuid
)
```
res.code = 204 if experiment was deleted successfully
---
Close #1124
Relate https://github.com/SwanHubX/SwanLab-Docs/pull/189

feat(api): delete project & experiment

---

swanlab/package.py
test/unit/test_package.py

Improves host string processing in save_key by correctly removing trailing '/api' and whitespace. Adds unit tests to verify correct host handling and extends HostFormatter test coverage.
Thanks to https://github.com/kingdee for the feedback.

Fix host string handling in save_key and add tests

---

swanlab/data/porter/__init__.py
swanlab/data/porter/datastore.py
swanlab/package.py
test/unit/test_package.py

Added explicit flush and fsync calls after writing to the netrc file to ensure data is written to disk. Also simplified file creation logic when the file does not exist.
这应该能解决单测偶尔报错的问题

Ensure netrc file is properly flushed and synced

---

swanlab/data/callbacker/__init__.py
swanlab/data/utils.py

Removed the import of LocalRunCallback from the callbacker module and updated dynamic imports in utils.py to only include necessary callbacks.
修复如果 dashboard 没安装时即使没有使用本地模式也报错的问题

Remove LocalRunCallback import and update callback imports

---

swanlab/data/sdk.py
test/unit/data/test_sdk.py

Moved the defaulting of the 'resume' parameter to later in the initialization process to ensure correct precedence. Added unit tests to verify that the resume parameter can be set via environment variable and that explicit arguments override environment variables.

Fix resume parameter handling and add env var tests

---

swanlab/data/run/key.py

Updated the logic for assigning section names and types based on key and section_type. Now, PUBLIC and CUSTOM types use the prefix before a slash in the key as the section name, and CUSTOM type is treated as PUBLIC. SYSTEM, PINNED, and HIDDEN types do not assign a section name.

Refactor section assignment logic in SwanLabKey

---

swanlab/data/run/key.py
test/unit/data/run/test_key.py

Corrected the keys used to extract 'expected' and 'got' values from the error dictionary to 'excepted' and 'data_class', ensuring proper error handling in the SwanLabKey class.
修复了面对错误类型图表时 resume 出错的问题

Fix error key usage in SwanLabKey class

---

swanlab/proto/v0.py

在使用最新版的 `accelerate==1.9.0` 与 `swanlab[dashboard]==0.6.7` 进行本地实验记录时（`mode="local"`），我在 **Windows 平台** 下遇到了编码相关的崩溃。具体来说：
- 项目运行到 `swanlab.config["FRAMEWORK"] = "🤗Accelerate"` 时触发异常
- 根因是 swanlab 内部在读取 YAML/JSON 文件时未指定编码，Windows 默认使用 `gbk`，无法解析其中包含的 emoji 字符（如 🤗）
---
测试环境：
- OS: Windows 11
- Python 版本: 3.13.5
- accelerate==1.9.0
- swanlab==0.6.7（含 dashboard）
复现代码（仅在官方示例基础上添加 `mode="local"`）：
```python
from accelerate import Accelerator
accelerator = Accelerator(log_with="swanlab")
accelerator.init_trackers(
project_name="accelerator",
config={"dropout": 0.1, "learning_rate": 1e-2},
init_kwargs={"swanlab": {"experiment_name": "hello_world", "mode": "local"}}
)
for i in range(100):
accelerator.log({"train_loss": 1.12, "valid_loss": 0.8}, step=i + 1)
accelerator.end_training()
```
```shell …
```

fix: Windows 系统下，与 accelerate 一起使用时，local 模式因默认 gkb 编码导致报错

---

swanlab/data/run/key.py
test/resume/must.py
test/unit/data/run/test_key.py

修复 sync  一个 resume 的 folder 会出现的列类型错误
现在的设计是 resume 时硬件监控不会开启，但是考虑到后续的更新，在backup file文件夹依旧保存了硬件监控相关的列信息
当 sync resume 的文件夹时就出现了列的类型错误，导致显示问题

fix: sync resume folder

---

swanlab/api/experiment.py
swanlab/api/main.py

- When integrating SwanLab's OpenAPI into MCP Server tools, the `get_metrics` function frequently throws a `list index out of range` error, preventing proper functionality. This pull request fixed this bug.
Through systematic investigation and collaborative debugging, we identified the following error chain:
1. Immediate Cause: Line 135 in `swanlab/api/experiment.py` attempts to access `[0]` from an empty list
```python
resp.data = list(resp.data.values())[0]  # Line 135
```
2. Underlying Cause: Line 131 returns an empty response (`resp.data` is empty)
```python
resp = self.http.post("/house/metrics/summaries", data=[data], params={})  # Line 131
```
3. Root Cause: The HTTP request returns empty results due to incorrect field naming in the data parameter format
Closes: #1244

fix(api): fix method `get_summary` in class `OpenApi`

---

requirements.txt

Updated the pydantic dependency to require a version less than 3, instead of just >=2.9.0. This may help avoid compatibility issues with breaking changes in pydantic 3.x.
Thanks to @GuoPingPan

chore: restrict pydantic version

---

swanlab/api/base.py
swanlab/core_python/__init__.py
swanlab/core_python/auth/providers/api_key.py
swanlab/core_python/client/__init__.py
swanlab/core_python/session.py
test/unit/core_python/test_client.py
test/unit/core_python/test_session.py

Raised the total HTTP retry attempts from 3 to 10 and increased the backoff factor to 0.5 in the Client class. Updated the corresponding unit test to match the new retry logic and simplified response assertions.
for: #1252

chore: opt retry params 

---

requirements.txt

在 #1257 中规定的pydantic版本有些宽松了，进行了一些调整
Closes: #1264

fix: change pydantic version constraint in requirements

---

swanlab/api/experiment.py
swanlab/cli/commands/__init__.py
swanlab/cli/commands/auth/__init__.py
swanlab/cli/commands/auth/verify.py
swanlab/cli/main.py
test/unit/cli/test_cli_verify.py

Introduces a new 'verify' CLI command to validate the current user login status. Updates command registration and imports to include the new command.
Just use `swanlab verify` to check login status

Add verify command to check login status

---

swanlab/core_python/client/__init__.py
swanlab/data/callbacker/callback.py
swanlab/data/callbacker/cloud.py
swanlab/data/run/main.py
swanlab/data/store.py

增加对 ctrl+c 的识别，提供一种新的实验状态
Related: #425

feat: add interrupt handling for experiment termination

---

.github/workflows/test-when-pr.yml
swanlab/data/modules/custom_charts/metrics.py

Added try-except blocks to provide clearer ImportError messages for missing scikit-learn and numpy dependencies in custom_charts/metrics.py. Updated the GitHub Actions workflow to run a basic import of swanlab after installing base dependencies, improving early detection of import issues.

Improve dependency checks and imports in metrics module
